### PR TITLE
0.10.7.0

### PR DESCRIPTION
**Pull request by jackcryp**

### CODE REVIEW

**Comment by MaxGuevara** [comment]
Daemon compiles ok.

QT fails with this error:

  CXX      qt/qt_libquarkqt_a-walletframe.o
qt/walletframe.cpp: In member function ‘void WalletFrame::gotoMasternodePage()’:
qt/walletframe.cpp:126:20: error: ‘class WalletView’ has no member named ‘gotoMasternodePage’
         i.value()->gotoMasternodePage();
                    ^

**Comment by jackcryp** [comment]
seems you are working on a error version? I didn’t get this issue as I have already compiled a qt wallet.发自我的iPhone------------------ Original ------------------From: MaxGuevara  <notifications@github.com>Date: Fri,Jun 21,2019 0:48 AMTo: quark-project/quark <quark@noreply.github.com>Cc: Jack Crypto <jackcryp@gmail.com>, Author <author@noreply.github.com>Subject: Re: [quark-project/quark] 0.10.7.0 (#43)Daemon compiles ok.
QT fails with this error:
CXX      qt/qt_libquarkqt_a-walletframe.o
qt/walletframe.cpp: In member function ‘void WalletFrame::gotoMasternodePage()’:
qt/walletframe.cpp:126:20: error: ‘class WalletView’ has no member named ‘gotoMasternodePage’
i.value()->gotoMasternodePage();
^

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/quark-project/quark/pull/43?email_source=notifications\u0026email_token=AMKL6K4Q4EJAFS6MESPXVYTP3OYEVA5CNFSM4HW5VTJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYF7MOY#issuecomment-504100411",
"url": "https://github.com/quark-project/quark/pull/43?email_source=notifications\u0026email_token=AMKL6K4Q4EJAFS6MESPXVYTP3OYEVA5CNFSM4HW5VTJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYF7MOY#issuecomment-504100411",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yagami1988** [comment]
> Daemon compiles ok.
> 
> QT fails with this error:
> 
> CXX qt/qt_libquarkqt_a-walletframe.o
> qt/walletframe.cpp: In member function ‘void WalletFrame::gotoMasternodePage()’:
> qt/walletframe.cpp:126:20: error: ‘class WalletView’ has no member named ‘gotoMasternodePage’
> i.value()->gotoMasternodePage();
> ^

0.10.7.0 is based on 0.10.6.5
So the real merge object for 0.10.7.0 is 0.10.6.5，Not 0.10.7
Since the main code base had not been updated 0.10.6.5 at that time
So I couldn't make the right request

**Comment by MaxGuevara** [comment]
Compiling from:

git remote -v
origin	https://github.com/jackcryp/quark.git (fetch)
origin	https://github.com/jackcryp/quark.git (push)

git branch
* 0.10.7.0
  master

**Pull request closed without merging**
